version: "3.7"

services:

   intento:
      image: intento:v1
      ports:
         - 8000:80
      volumes:
         - ./src:/var/www/html/

   mysql:
      image: mysql:5.7
      volumes:
         - ./mysql-data:/var/lib/mysql
      environment:
         MYSQL_ROOT_PASSWORD: portal
         MYSQL_DATABASE: pajarera

   phpmyadmin:
       image: phpmyadmin:5-apache
       ports:
         - 8080:80
       environment:
         - PMA_ARBITRARY=1
