version: "3.7"

services:

   st456w:
      image: st456-test:v1
      ports:
         - 5000:80

   mysql:
      image: mysql:5.7
      volumes:
         - ./mysql-data:/var/lib/mysql
      environment:
         MYSQL_ROOT_PASSWORD: portal
         MYSQL_DATABASE: st456w
